### PR TITLE
Protected

### PR DESCRIPTION
**Pull request by earlAchromatic**
tlc

### CODE REVIEW

**Comment by earlAchromatic** [comment]
This change is [Reviewable](https://reviewable-dev-jacob-default-rtdb.firebaseapp.com/reviews/earlachromatic/11ty-vue-pragmatic-components/9)

**Comment by earlAchromatic** [comment]
Just a thought.

**Comment by earlAchromatic** [comment]
is this real?

**Comment by earlAchromatic** [comment]
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

is this real?
</blockquote></details>

dsf. gg

**Comment by earlAchromatic** [comment]
*[`-- commits` line 27 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9FNWZ4ClSkXV3Mz7Ni):*
sdf

**Comment by earlAchromatic** [comment]
*[`-- commits` line 27 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9FNWZ4ClSkXV3Mz7Ni):*
sdf

**Review by prcl8tr — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @earlAchromatic and @prcl8tr)

___
*[`.eleventy.js` line 24 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N93E0_L29ULxhAEI3vu:-N93E0_L29ULxhAEI3vv:bgc90cv) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/0d104a26da8aa00fe25a04353cbde7d1af6fb9fa/.eleventy.js#L24)):*
> ```JavaScript
>   return {
>     dir: {
>       input: 'src',
> ```

Whoa, this doesn't look right.

**Review by prcl8tr — COMMENTED** [review]
> Reviewed 15 of 16 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9)* status: all files reviewed, 4 unresolved discussions (waiting on @earlAchromatic and @prcl8tr)

**Review by earlAchromatic — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9)* status: all files reviewed, 20 unresolved discussions (waiting on @earlAchromatic and @prcl8tr)

___
*[`-- commits` line 27 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9FNWZ4ClSkXV3Mz7Ni):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

sdf
</blockquote></details>

dffds fdsf 



_Code quote (i):_
```
- 4830d22: revert package.json
```



_Code quote (ii):_
```
- 4830d22: revert package.json
```
___
*[`.eleventy.js` line 24 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N93E0_L29ULxhAEI3vu:-NAfV20cE9iZxRQ1r8xB:b-896fix) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/0d104a26da8aa00fe25a04353cbde7d1af6fb9fa/.eleventy.js#L24)):*
<details><summary><i>Previously, prcl8tr wrote…</i></summary><blockquote>

Whoa, this doesn't look right.
</blockquote></details>

Done.
___
*[`package-lock.json` line 20 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HzcPX2XpbUAAiElb2:-N9HzcPX2XpbUAAiElb3:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/4a4fc8e30896380e15558ffaf2e4c74f4ee0bb5d/package-lock.json#L20)):*
> ```JSON
>         "jsdom": "^19.0.0",
>         "vite": "^2.9.1",
>         "vue": "^3.2.31"
> ```

sdf 



_Code quote:_
```JSON
        "vue": "^3.2.31"
```
___
*[`package-lock.json` line 117 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9Hr03D8hwouNX_B7Dh:-N9Hr03D8hwouNX_B7Di:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/4a4fc8e30896380e15558ffaf2e4c74f4ee0bb5d/package-lock.json#L117)):*
> ```JSON
>       }
>     },
>     "node_modules/@11ty/eleventy-utils": {
> ```

sdf 



_Code quote:_
```JSON
        "url": "https://opencollective.com/11ty"




































      }
    },
    "node_modules/@11ty/eleventy-utils": {
```
___
*[`package-lock.json` line 119 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HzapV1KZrg8xJcNmw:-N9HzapV1KZrg8xJcNmx:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L119)):*
> ```JSON
>     "node_modules/@11ty/eleventy-plugin-vite/node_modules/vite": {
>       "version": "2.9.14",
>       "resolved": "https://registry.npmjs.org/vite/-/vite-2.9.14.tgz",
> ```

sdf 



_Code quote (i):_
```JSON
      "resolved": "https://registry.npmjs.org/vite/-/vite-2.9.14.tgz",
```



_Code quote (ii):_
```JSON
      "resolved": "https://registry.npmjs.org/vite/-/vite-2.9.14.tgz",
```



_Code quote (iii):_
```JSON
      "resolved": "https://registry.npmjs.org/vite/-/vite-2.9.14.tgz",
```
___
*[`package-lock.json` line 130 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HqxypENz7iGQffcIo:-N9HqxypENz7iGQffcIp:bb7odek) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L130)):*
> ```JSON
>         "vite": "bin/vite.js"
>       },
>       "engines": {
> ```

sd f



_Code quote (i):_
```JSON
        "esbuild": "^0.14.27",
        "postcss": "^8.4.13",
        "resolve": "^1.22.0",
        "rollup": "^2.59.0"
      },
      "bin": {
        "vite": "bin/vite.js"
      },
      "engines": {
```



_Code quote (ii):_
```JSON
      "dependencies": {
        "esbuild": "^0.14.27",
        "postcss": "^8.4.13",
        "resolve": "^1.22.0",
        "rollup": "^2.59.0"
      },
      "bin": {
        "vite": "bin/vite.js"
      },
      "engines": {
```
___
*[`package-lock.json` line 136 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HxdbY30YlTURaQJwb:-N9HxdbY30YlTURaQJwc:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L136)):*
> ```JSON
>         "fsevents": "~2.3.2"
>       },
>       "peerDependencies": {
> ```

sdf 
___
*[`package-lock.json` line 146 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HrIYW9-d2E3mX4DHK:-N9HrIYW9-d2E3mX4DHL:b-7jl8ut) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L146)):*
> ```JSON
>         },
>         "sass": {
>           "optional": true
> ```

sadf 



_Code quote:_
```JSON
          "optional": true
```
___
*[`package-lock.json` line 153 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HrMho9J9mcezRMXVR:-N9HrMho9J9mcezRMXVS:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L153)):*
> ```JSON
>       }
>     },
>     "node_modules/@11ty/eleventy-utils": {
> ```

sdf 



_Code quote:_
```JSON
        "sass": "*",
        "stylus": "*"
      },
      "peerDependenciesMeta": {
        "less": {
          "optional": true
        },
        "sass": {
          "optional": true
        },
        "stylus": {
          "optional": true
        }
      }
    },
    "node_modules/@11ty/eleventy-utils": {
```
___
*[`package-lock.json` line 928 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HtAH59DRbo6eNxsii:-N9HtAH59DRbo6eNxsij:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/4a4fc8e30896380e15558ffaf2e4c74f4ee0bb5d/package-lock.json#L928)):*
> ```JSON
>         "esbuild-freebsd-64": "0.14.29",
>         "esbuild-freebsd-arm64": "0.14.29",
>         "esbuild-linux-32": "0.14.29",
> ```

sdf 



_Code quote:_
```JSON
        "esbuild-linux-32": "0.14.29",
```
___
*[`package-lock.json` line 939 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HtpJ8AbZqNaTSYsxT:-N9HtpJ91ZdivZlLqCQ1:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/4a4fc8e30896380e15558ffaf2e4c74f4ee0bb5d/package-lock.json#L939)):*
> ```JSON
>         "esbuild-openbsd-64": "0.14.29",
>         "esbuild-sunos-64": "0.14.29",
>         "esbuild-windows-32": "0.14.29",
> ```

sdf 



_Code quote:_
```JSON
        "esbuild-linux-mips64le": "0.14.29",
        "esbuild-linux-ppc64le": "0.14.29",
        "esbuild-linux-riscv64": "0.14.29",
        "esbuild-linux-s390x": "0.14.29",
        "esbuild-netbsd-64": "0.14.29",
        "esbuild-openbsd-64": "0.14.29",
        "esbuild-sunos-64": "0.14.29",
        "esbuild-windows-32": "0.14.29",
```
___
*[`package-lock.json` line 981 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9HlwvjA6lACSixYLnn:-N9HlwvjA6lACSixYLno:b2nic5s) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/4a4fc8e30896380e15558ffaf2e4c74f4ee0bb5d/package-lock.json#L981)):*
> ```JSON
>         "x64"
>       ],
>       "optional": true,
> ```

sdf



_Code quote:_
```JSON
      "optional": true,
```
___
*[`package-lock.json` line 982 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9Hm1026qG4ESiig2DS:-N9Hm1026qG4ESiig2DT:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L982)):*
> ```JSON
>     "node_modules/esbuild-android-64": {
>       "version": "0.14.50",
>       "resolved": "https://registry.npmjs.org/esbuild-android-64/-/esbuild-android-64-0.14.50.tgz",
> ```

sdf 



_Code quote:_
```JSON
      "resolved": "https://registry.npmjs.org/esbuild-android-64/-/esbuild-android-64-0.14.50.tgz",
```
___
*[`package-lock.json` line 1004 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9FREYzAz7pzDdYApCX:-N9FREYzAz7pzDdYApCY:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L1004)):*
> ```JSON
>       "optional": true,
>       "os": [
>         "android"
> ```

sdf 



_Code quote:_
```JSON
        "android"
```
___
*[`package-lock.json` line 1032 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9bmgdO0bwH4BbHnQrs:-N9bmgdO0bwH4BbHnQrt:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L1032)):*
> ```JSON
>         "arm64"
>       ],
>       "optional": true,
> ```

sdf 
___
*[`package-lock.json` line 1794 at r2](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9boJ1j-7HzxsvBvdzl:-N9boJ1j-7HzxsvBvdzm:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/faefab00e303dacb19d4eb0a8d33f370eff1089f/package-lock.json#L1794)):*
> ```JSON
>       "resolved": "https://registry.npmjs.org/is-core-module/-/is-core-module-2.9.0.tgz",
>       "integrity": "sha512-+5FPy5PnwmO3lvfMb0AsoPaBG+5KHUI0wYFXOtYPnVVVspTFUuMZNfNaNVRt3FZadstu2c8x23vykRW/NBoU6A==",
>       "dependencies": {
> ```

sdf 
___
*[`package-lock.json` line 1148 at r3](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-NADmRqi5UtGAx74r5Q-:-NADmRqi5UtGAx74r5Q0:b2ni28f) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/705f08699f3015837f4e3708edeeac5e115ae230/package-lock.json#L1148)):*
> ```JSON
>       "version": "0.14.50",
>       "resolved": "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.14.50.tgz",
>       "integrity": "sha512-xWCKU5UaiTUT6Wz/O7GKP9KWdfbsb7vhfgQzRfX4ahh5NZV4ozZ4+SdzYG8WxetsLy84UzLX3Pi++xpVn1OkFQ==",
> ```

ewf



_Code quote:_
```JSON
      "integrity": "sha512-xWCKU5UaiTUT6Wz/O7GKP9KWdfbsb7vhfgQzRfX4ahh5NZV4ozZ4+SdzYG8WxetsLy84UzLX3Pi++xpVn1OkFQ==",
```
___
*[`README.md` line 25 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N93EkqzAWxcgdbojbNN:-N93EkqzAWxcgdbojbNO:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/0d104a26da8aa00fe25a04353cbde7d1af6fb9fa/README.md#L25)):*
> ```Markdown
> its a vue only solution
> focuses on 1 framework
> focuses on authorability (no shortcodes)
> ```

sdf 
___
*[`vite.config.js` line 4 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N93Ejsj8oAQAi5RhSCR:-N93Ejsj8oAQAi5RhSCS:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/0d104a26da8aa00fe25a04353cbde7d1af6fb9fa/vite.config.js#L4)):*
> ```JavaScript
> import vue from '@vitejs/plugin-vue';
> import {URL } from 'url';
> ```

sdf 
___
*[`components/myHeader.vue` line 19 at r3](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9#-N9t8-ar2vC9YUL5laVL:-N9t8-ar2vC9YUL5laVM:bb7of0w) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/705f08699f3015837f4e3708edeeac5e115ae230/components/myHeader.vue#L19)):*
> ```Vue
>     return new Promise((resolve) => {
>       setTimeout(() => {
>         resolve(import('./SlottedComp.vue'));
> ```

sdf 



_Code quote:_
```Vue
      }, 5000);
    });
  },
  loadingComponent: Loading,
  delay: 400,
});

const clicker = ref(true);

const clicked = () => {
  clicker.value = true;
};
</script>
<template>
  <h2>Slot here</h2>
  <slot>steady does it champo</slot>
</template>
```

**Review by prcl8tr — APPROVED** [review]
> Dismissed @earlAchromatic from 20 discussions.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Pull request merged**
