### PR TITLE
rename header

### PR DESCRIPTION
**Pull request by earlAchromatic**
This change is [Reviewable](https://reviewable-dev-jacob-default-rtdb.firebaseapp.com/reviews/earlachromatic/11ty-vue-pragmatic-components/14)

### CODE REVIEW

**Comment by earlAchromatic** [comment]
This change is [Reviewable](https://reviewable-dev-jacob-default-rtdb.firebaseapp.com/reviews/earlachromatic/11ty-vue-pragmatic-components/14)

**Comment by earlAchromatic** [comment]
@oscl8tr

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/earlAchromatic/11ty-vue-pragmatic-components/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Comment by oscl8tr** [comment]
:lgtm:

**Comment by oscl8tr** [comment]
*[`-- commits` line 9 at r3](http://localhost:8080/reviews/earlAchromatic/11ty-vue-pragmatic-components/14#-NQSzc6WCbZTd0pWFGpB):*
this line

**Comment by earlAchromatic** [comment]
*[`components/myHeader.vue` line 0 at r3](http://localhost:8080/reviews/earlAchromatic/11ty-vue-pragmatic-components/14#-NTX6_yfCaFcMj4QJxLI:-NTX6_yfCaFcMj4QJxLJ:bb7jfoj) ([raw file](https://github.com/earlAchromatic/11ty-vue-pragmatic-components/blob/52f2a1dea3d982d49a61525361561d04c0017c63/components/myHeader.vue#L0)):*
kjhg

**Comment by earlAchromatic** [comment]
*[`components/myHeader.vue` line 0 at r3](http://localhost:8080/reviews/earlAchromatic/11ty-vue-pragmatic-components/14#-NTX6bzr0v-dCRUebsup:-NTX6bzr0v-dCRUebsuq:bb7evs5) ([raw file](https://github.com/earlAchromatic/11ty-vue-pragmatic-components/blob/52f2a1dea3d982d49a61525361561d04c0017c63/components/myHeader.vue#L0)):*
dfge

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](http://localhost:8080/reviews/earlAchromatic/11ty-vue-pragmatic-components/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Pull request merged**
