### PR TITLE
Revert "Protected"

### PR DESCRIPTION
**Pull request by earlAchromatic**
Reverts earlAchromatic/11ty-vue-pragmatic-components#9

- - -
This change is [Reviewable](https://reviewable-dev-jacob-default-rtdb.firebaseapp.com/reviews/earlachromatic/11ty-vue-pragmatic-components/26)

### CODE REVIEW

**Comment by earlAchromatic** [comment]
This change is [Reviewable](https://reviewable-dev-jacob-default-rtdb.firebaseapp.com/reviews/earlachromatic/11ty-vue-pragmatic-components/26)

**Review by prcl8tr — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26)* status: 3 of 16 files reviewed, 1 unresolved discussion (waiting on @earlAchromatic and @prcl8tr)

___
*[`package-lock.json` line 121 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NBwmhiw1XpCkKrqaGNV:-NBwmhiw1XpCkKrqaGNW:b-n032ok) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/be4c9f1afffa01bb441cab07e25f0424aaec5204/package-lock.json#L121)):*
> ```JSON
>       "resolved": "https://registry.npmjs.org/vite/-/vite-2.9.14.tgz",
>       "integrity": "sha512-P/UCjSpSMcE54r4mPak55hWAZPlyfS369svib/gpmz8/01L822lMPOJ/RYW6tLCe1RPvMvOsJ17erf55bKp4Hw==",
>       "dependencies": {
> ```

Is this the best way?

**Review by earlAchromatic — COMMENTED** [review]
> Dismissed @prcl8tr from a discussion.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26)* status: 3 of 16 files reviewed, all discussions resolved (waiting on @prcl8tr)

**Comment by earlAchromatic** [comment]
*[`package-lock.json` line 121 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NBwmhiw1XpCkKrqaGNV:-NCBoEYW-cGMZ9q7mHEI:b2ni1ea) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/be4c9f1afffa01bb441cab07e25f0424aaec5204/package-lock.json#L121)):*
<details><summary><i>Previously, prcl8tr wrote…</i></summary><blockquote>

Is this the best way?
</blockquote></details>

dsf

**Comment by earlAchromatic** [comment]
Here is a fact.

**Comment by earlAchromatic** [comment]
and another.

**Comment by oscl8tr** [comment]
*[`package-lock.json` line 18 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NL2lENVB0es5W7mKvzG:-NL2lENW34H-oy-zcSAP:b70qids) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/b0d3e7b6f579f5d8636fc2ebd9293769fb855318/package-lock.json#L18)):*
> ```JSON
>         "html-template-tag": "^4.0.0",
>         "http-server": "^14.1.0",
>         "jsdom": "^19.0.0",
> ```

I have a thought.

**Comment by oscl8tr** [comment]
*[`package-lock.json` line 18 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NL2lENVB0es5W7mKvzG:-NL2lYHy5jfck0LVZLH8:b-dexbvz) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/b0d3e7b6f579f5d8636fc2ebd9293769fb855318/package-lock.json#L18)):*
<details><summary><i>Previously, oscl8tr wrote…</i></summary><blockquote>

I have a thought.
</blockquote></details>

its serious now.

**Review by earlAchromatic — COMMENTED** [review]
> Dismissed @oscl8tr from a discussion.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26)* status: 3 of 16 files reviewed, 2 unresolved discussions (waiting on @oscl8tr and @prcl8tr)

___
*[`package-lock.json` line 112 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NDn0AMu8rEcTBSL5yPm:-NDn0AMu8rEcTBSL5yPn:bb7oh97) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/b0d3e7b6f579f5d8636fc2ebd9293769fb855318/package-lock.json#L112)):*
> ```JSON
>         "node": ">=12"
>       },
>       "funding": {
> ```

sgdf
___
*[`package-lock.json` line 132 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NDfMm6o6C71mTJ8LpV8:-NDfB7Qg1s3-w4bOAd5R:bb41v4r) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/be4c9f1afffa01bb441cab07e25f0424aaec5204/package-lock.json#L132)):*
> ```JSON
>       "engines": {
>         "node": ">=12.2.0"
>       },
> ```

This draft will block

**Comment by oscl8tr** [comment]
*[`-- commits` line 2 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NLbfVNG7rCe-Otq5_Zg):*
can i be a part of this?

**Review by earlAchromatic — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26)* status: 3 of 16 files reviewed, 3 unresolved discussions (waiting on @earlAchromatic, @oscl8tr, and @prcl8tr)

*[a discussion](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NLbjIQB9HNu4Ht6lYYD:-NDfM9S2D3IUUW7UmN_7:bo4rqn9) (no related file):*
>  
sg

___
*[a discussion](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NLbnos-1idZglhCqeF8:-NLbnos-1idZglhCqeF9:b2nic5s) (no related file):*
sdf

___
___
*[`-- commits` line 2 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26#-NLbfVNG7rCe-Otq5_Zg):*
<details><summary><i>Previously, oscl8tr wrote…</i></summary><blockquote>

can i be a part of this?
</blockquote></details>

Done.

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26)* status: all files reviewed, 1 unresolved discussion (waiting on @oscl8tr)

**Review by earlAchromatic — COMMENTED** [review]
> Dismissed @oscl8tr from a discussion.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Review by prcl8tr — APPROVED** [review]
> Reviewed 13 of 16 files at r1.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Pull request merged**
