### PR TITLE
Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "simple lines""""""""

### PR DESCRIPTION
**Pull request by earlAchromatic**
Reverts earlAchromatic/11ty-vue-pragmatic-components#24

- - -
This change is [Reviewable](https://reviewable-dev-jacob-default-rtdb.firebaseapp.com/reviews/earlachromatic/11ty-vue-pragmatic-components/25)

### CODE REVIEW

**Comment by earlAchromatic** [comment]
This change is [Reviewable](https://reviewable-dev-jacob-default-rtdb.firebaseapp.com/reviews/earlachromatic/11ty-vue-pragmatic-components/25)

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Comment by earlAchromatic** [comment]
sdf

**Comment by earlAchromatic** [comment]
sadf f

**Comment by earlAchromatic** [comment]
asdfd.

**Comment by earlAchromatic** [comment]
dsf. fd

**Comment by earlAchromatic** [comment]
sdf dseee

**Comment by earlAchromatic** [comment]
lets make it 5

**Comment by earlAchromatic** [comment]
Lets make it 6.

**Comment by earlAchromatic** [comment]
*[`lines.js` line 20 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NBnLMpxB63t9Q1V4N0V:-NBnLMpxB63t9Q1V4N0W:b2ni1ea) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L20)):*
> ```JavaScript
> // 96 Col
>                                                                                                     
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ```

dsf



_Suggestion:_
```JavaScript
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



jkhjkhkhkkjhjkhkhkhjhkjjjjfsdfsdf

jjjjjjjkjhkjshdjkfklsjdflkhjkbjkhjkhjk
sdfsdffsdfsdf

,jkkhjnkjn
















sdfsdfasdf
```

**Comment by earlAchromatic** [comment]
*[`lines.js` line 20 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NBnLMpxB63t9Q1V4N0V:-NCQNSfw7G0KfFegTLJ3:b32wwp) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L20)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

dsf
</blockquote></details>

sg

**Comment by earlAchromatic** [comment]
*[`lines.js` line 20 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NBnLMpxB63t9Q1V4N0V:-NCQNTrs4BSY85p8d25x:b2nhyw8) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L20)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

sg
</blockquote></details>

ags

**Comment by earlAchromatic** [comment]
*[`lines.js` line 8 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NCQOG7t-1aXC_mFSfSl:-NCQOG7u56ZrMH2Rpxoj:bb7d8e1) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L8)):*
> ```JavaScript
> // 99 Col
>                                                                                                     
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ```

asdf

**Comment by earlAchromatic** [comment]
*[`lines.js` line 8 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NCQOG7t-1aXC_mFSfSl:-NCQOLUy5V9M-bR_4umA:b2nic5s) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L8)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

sdf
</blockquote></details>

sdf

**Comment by earlAchromatic** [comment]
Here:

```
enter(el, done) {
    if (!this.animate) return;
    this.$refs.comment.style.height = '';
    anime({
      targets: this.$refs.comment,
      duration: 5000,
      translateY: [-this.$refs.comment.offsetHeight, 0],
      height: [0, this.$refs.comment.offsetHeight],
      easing: 'linear',
      complete: done
    });
  }

  leave(el, done) {
    if (!this.animate) return;
    this.$refs.comment.style.height = '';
    anime({
      targets: this.$refs.comment,
      duration: 5000,
      translateY: [0, -this.$refs.comment.offsetHeight - this.$refs.comment.offsetTop],
      height: [this.$refs.comment.offsetHeight, 0],
      easing: 'linear',
      complete: done
    });
  }
```

**Comment by earlAchromatic** [comment]
*[`lines.js` line 8 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NCQOG7t-1aXC_mFSfSl:-NCYbtRa9Mw2KgptnId-:b2nic5s) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L8)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

sdf
</blockquote></details>

sdf



_Code snippet (i):_
```JavaScript
sdf
```



_Code snippet (ii):_
```JavaScript
dsgdsfasdf
```



_Code snippet (iii):_
```JavaScript
saddfdfs
```

**Comment by earlAchromatic** [comment]
#4

**Comment by earlAchromatic** [comment]
@prcl8tr

**Comment by earlAchromatic** [comment]
stub

**Comment by earlAchromatic** [comment]
dsg

**Comment by earlAchromatic** [comment]
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

stub
</blockquote></details>

more

**Comment by earlAchromatic** [comment]
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

more
</blockquote></details>

more +1

**Comment by earlAchromatic** [comment]
*[`lines.js` line 20 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NBnLMpxB63t9Q1V4N0V:-NDKBQF25mI4LDgnuX9a:b-7tfo6p) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L20)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

ags
</blockquote></details>

add s



_Code quote:_
```JavaScript
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      <svg width="30" height="20" viewBox="0 0 30 20" fill="none" xmlns="http://www.w3.org/2000/svg">
// 96 Col

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Review by earlAchromatic — COMMENTED** [review]
sg

> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-:-NDnxQK5EaZ0qWGdqvOR:b32wwp)* status: all files reviewed, 6 unresolved discussions (waiting on @prcl8tr)

___
*[`lines.js` line 3 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NDn3HotD4mYHBqPhybM:-NDn3HotD4mYHBqPhybN:bb2m90d) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L3)):*
> ```JavaScript
> // 100 Col
>                                                                                                     
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ```

erretr 
___
*[`lines.js` line 9 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NDn2sI0DMrN7s_2khtw:-NDn2sI0DMrN7s_2khtx:b-kq9qs9) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L9)):*
> ```JavaScript
>                                                                                                     
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>       <svg width="30" height="20" viewBox="0 0 30 20" fill="none" xmlns="http://www.w3.org/2000/svg">
> ```

sdffsd
___
*[`lines.js` line 13 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NDjuxTN1gs6p-uZ-Rdq:-NDjuxTOBIu-95G58Imv:b2ni6dg) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L13)):*
> ```JavaScript
>                                                                                                     
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>       <svg width="30" height="20" viewBox="0 0 30 20" fill="none" xmlns="http://www.w3.org/2000/svg">
> ```

kjh

**Review by earlAchromatic — COMMENTED** [review]
sg

> *[Reviewable](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-:-NDnxYs94VqVGqgZplUP:b32wwp)* status: all files reviewed, 6 unresolved discussions (waiting on @prcl8tr)

**Comment by prcl8tr** [comment]
comment

**Comment by earlAchromatic** [comment]
*[`lines.js` line 20 at r1](http://localhost:8080/reviews/earlachromatic/11ty-vue-pragmatic-components/25#-NEgujgL4GzMxuW90GqE:-NEgujgL4GzMxuW90GqF:b2nic5t) ([raw file](https://github.com/earlachromatic/11ty-vue-pragmatic-components/blob/159f846d471057238bdf2b6765eed6bd989907a3/lines.js#L20)):*
> ```JavaScript
> // 96 Col
>                                                                                                     
> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ```

sdg

**Pull request merged**
